### ISSUE TITLE
是否可以支持Mac开发调试

### ISSUE THREAD

**Issue by hongyang-li** [jamesiter/JimV-C#10]
多数情况下在Mac下进行开发，请问是否支持Mac下开发，具体注意事项有哪些，麻烦指教一下。

**Comment by jamesiter** [comment]
我是通过pycharm远程debug模式开发的。即代码在远程linux服务器上运行，本地可以在ide上下断点调试。JimV-N 必须运行在物理机上。我的开发机也是MAC。
