### ISSUE TITLE
[说明文档] 手动安装步骤缺少操作

### ISSUE THREAD

**Issue by yifengyou** [jamesiter/JimV-C#11]
# 启动JimV-C
/home/www/sites/JimV-C/startup.sh
----
启动服务之前应该先
cp -v /usr/local/JimV-C/misc/jimvc.service /etc/systemd/system/jimvc.service
systemctl daemon-reload

不然很明显错误
[root@centos7 www]# /home/www/sites/JimV-C/startup.sh
Failed to start jimvc.service: Unit not found.
Unit jimvc.service could not be found.

**Comment by yifengyou** [comment]
手动安装步骤还缺少其他内容，

 jimvc.service文件以及指定了JimV-C目录地址，但是手动步骤放在 
su - www -c "git clone https://github.com/jamesiter/JimV-C.git ~/sites/JimV-C"
应该放在 WorkingDirectory=/usr/local/JimV-C/ 不然服务器肯定启动不起来，还有venv-jimv位置也不一致


前后配置不一致，尴尬边挑错边跑起。。还不如一键安装来的顺畅~
哪怕文档中说明 文档仅供参考也好。。写详细一点省的其他人重复浪费时间

**Comment by jamesiter** [comment]
鼓励自动安装。未来会取消手动安装相关文档。项目首页已经删除手动安装链接。
